#! /bin/sh

out() {
  TARGET=`echo $1 | sed -E -e s/\\\\.flam3/.png/`
  echo --out=$TARGET $1
}

RENDER="cargo run --release --features libm -- --seed=foobar"

for SOURCE in `ls flam3/tests/render/*.flam3`
do
  $RENDER $(out $SOURCE)
done

$RENDER --earlyclip $(out flam3/tests/options/earlyclip.flam3)
