name: Tests

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy, llvm-tools-preview
      
      - name: Install grcov
        run: cargo install grcov

      - name: Check
        run: cargo check

      - name: Run tests
        run: cargo test --release --features libm
        continue-on-error: true
        env:
          RUSTFLAGS: -Cinstrument-coverage
          LLVM_PROFILE_FILE: flam3-%p-%m.profraw

      - name: Generate coverage
        run: grcov . --binary-path ./target/release/ -t coveralls -s . --token coveralls >coveralls.json

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          files: ./coveralls.json

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Rustfmt
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: fmt
          args: --check
